version: "3.9"
services:
  sensor-events:
    build: .
    container_name: "docker-sensor-events"
    ports:
      - 8090:8090
  mongodb:
    image: mongo:latest
    container_name: "mongodb-container"
    ports:
      - 27017:27017
  kafka:
    image: apache/kafka:3.7.0
    container_name: "kafka-container"
    ports:
      - 9092:9092