# Basepath to consult the API {{base-url}}{{basepath}}/sensor-events
basepath: /api
spring:
  data:
    # Database properties
    mongodb:
      host: localhost
      port: 27017
      database: sensor-events
  kafka:
    # Kafka properties
    bootstrap-servers:
      localhost:9092
    consumer:
      group-id:
        sensor-app-br
server:
  port: '8091'

