# Basepath to consult the API {{base-url}}{{basepath}}/sensor-events
basepath: /api

# Database properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sensor-events
server:
  port: '8091'

